version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only: 
  - master
configuration: Release
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init: git config --global core.autocrlf true
before_build: appveyor-retry dotnet restore -v Minimal
build:
  verbosity: minimal
test_script: dotnet test .\test --no-build
after_test: dotnet pack .\src -c %CONFIGURATION% --no-build /p:Version=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '.\src\**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/exact/api/v3/index.json
  api_key:
    secure: hkp/1wWL0SYrhqZEpLuVMhnEJVyQSdEZnfEgJGh2AlqIqINOnwGiX/0wNnRvffHHxw2PA93f48UAzkTBusgbYYQuT5p3sDwTStlONcJrtGI=
