version: '{build}'
image: Visual Studio 2017
branches:
  only:
  - master
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- git config --global core.autocrlf true
- ps: $Env:VERSIONSUFFIX = "pre-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build:
  verbosity: minimal
test_script:
- dotnet test .\test --no-build
after_test: 
- dotnet pack .\src -c Release --version-suffix %VERSIONSUFFIX%
artifacts:
- path: .\src\**\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/exact-packages/api/v2/package
  api_key:
    secure: rKYw2Re1ZlHj5PXrgO6jBETBo0sY66Lb46g/7WLETvFQvmQ9pskg94k0k1SDwFVt
  on:
    branch: master
