version: '{build}'
image: Visual Studio 2017
skip_tags: true
branches:
  only:
  - master
nuget:  
  disable_publish_on_pr: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
init:
- git config --global core.autocrlf true
- ps: $Env:PRERELEASE_VERSION = "pre-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -v Minimal
test_script:
- dotnet test .\test --no-build
after_test: 
- dotnet pack .\src -c Release --version-suffix %PRERELEASE_VERSION%
artifacts:
- path: .\src\**\*.nupkg
deploy:
- provider: NuGet
  server:   
  api_key:
    secure: rKYw2Re1ZlHj5PXrgO6jBETBo0sY66Lb46g/7WLETvFQvmQ9pskg94k0k1SDwFVt
  on:
    branch: master
